apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: swarmdev
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: api
  ports:
    - name: http
      port: 3001
      targetPort: http
      protocol: TCP
