apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: qdrant
  namespace: swarmdev
  labels:
    app.kubernetes.io/name: qdrant
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: qdrant
